#!/bin/bash

function	try_one() {
  tfm=`kpsewhich -format=tfm $1`
  echo "=== nts-tftopl $tfm ==="
  java tftopl "$tfm" > $tmp
  # echo "=== diff with tftopl $1 ==="
  tftopl $1 | diff $tmp -
}

tmp=/tmp/nts_tftopl$$.pl
trap "rm -f $tmp 2>/dev/null" 0 2 3 15
for i in "$@"; do try_one "$i"; done
